services:
  feedygg-db:
    image: guizmos/feedygg:latest
    container_name: FEEDYGG
    environment:
      - TZ=Europe/Paris
      - RSS_PASSKEY=VOTREPASSKEY
      - RSS_MOVIES_ID=2183
      - RSS_SERIES_ID=2184
      - RSS_SHOWS_ID=2182
      - RSS_ANIMATION_ID=2178
      - RSS_SPECTACLE_ID=2185
      - RSS_GAMES_ID=2161
      - TMDB_API_KEY=TMDBAPIKEY
      - IGDB_CLIENT_ID=IGDBCLIENTID
      - IGDB_CLIENT_SECRET=IGDBCLIENTSECRET
      - DB_PATH=/data/yggfeed.db
      - SYNC_INTERVAL_MINUTES=30
      - LOG_FILE=/data/yggfeed.log
      - LOG_MAX_BYTES=5242880
    volumes:
      - /volume1/Docker/FeedyGG/data:/data
    ports:
      - 7070:8080
    restart: unless-stopped
