name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'     # dès qu’un tag v1.0.0 est push → pipeline
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute image tags
        id: meta
        run: |
          IMAGE="${{ secrets.IMAGE_NAME }}"
          GIT_REF="${GITHUB_REF}"

          TAGS="$IMAGE:latest"

          if [[ "$GIT_REF" == refs/tags/v* ]]; then
            VERSION_WITH_V="${GIT_REF#refs/tags/}"   # v1.0.0
            VERSION="${VERSION_WITH_V#v}"            # 1.0.0
            TAGS="$TAGS,$IMAGE:$VERSION_WITH_V,$IMAGE:$VERSION"
          fi

          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          IFS=',' read -ra TAGS <<< "${{ steps.meta.outputs.tags }}"
          for TAG in "${TAGS[@]}"; do
            echo "Building image with tag: $TAG"
            docker build -t "$TAG" .
          done

      - name: Push Docker image
        run: |
          IFS=',' read -ra TAGS <<< "${{ steps.meta.outputs.tags }}"
          for TAG in "${TAGS[@]}"; do
            echo "Pushing image: $TAG"
            docker push "$TAG"
          done

  release:
    needs: build-and-push
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release with autogenerated notes
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
